exclude: 'docs'
fail_fast: false
repos:
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3.10
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    language_version: python3.10
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3.10
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    language_version: python3.10
    additional_dependencies: [screenpy==4.0.1, types-requests]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint --max-line-length=88 --disable=bad-continuation --disable=no-self-use --disable=too-few-public-methods --disable=invalid-name --disable=duplicate-code --disable=super-init-not-called --disable=fixme --disable=wildcard-import --disable=unused-wildcard-import --disable=unused-argument
    language: system
    types: [python]
