#! /bin/bash


ENV_VAR_PATH="./config/encrypted_env_vars"
ENVFILE_PATH="./.env"

echo "decrypting env vars"
cp $ENV_VAR_PATH $ENVFILE_PATH
# TODO: Use encryption once sops is added
# sops -d $ENV_VAR_PATH > $ENVFILE_PATH

# Start Xvfb - this was the problem causing chrome to crash (nowhere to render the browser!)
echo "starting Xvfb..."
sudo rm -f /tmp/.X*lock
export DISPLAY=:99
sudo Xvfb $DISPLAY -screen 0 1920x1080x24 -dpi 240 -ac +extension RANDR &

# run tests
echo "running tests..."
python3 -m pytest $@ --log-cli-level=INFO
